on:
  push:
    branches: [main]
  schedule:
    - cron: "0 3 * * 1"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        factorio_version: ["stable", "experimental"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Get latest version of ${{ matrix.factorio_version }}
        id: get_latest_version
        run: |
          echo ::set-output name=version::$(curl -sSL https://factorio.com/api/latest-releases | jq -r .${{ matrix.factorio_version }}.headless)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            ghcr.io/coderadu/factorio-docker:${{ matrix.factorio_version }}
            ghcr.io/coderadu/factorio-docker:${{ steps.get_latest_version.outputs.version }}
          build-args: |
            VERSION=${{ steps.get_latest_version.outputs.version }}
